edition = "2024"
style_edition = "2024"
unstable_features = true

blank_lines_upper_bound = 1
combine_control_expr = true
fn_single_line = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
ignore = []
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true

array_width = 90
attr_fn_like_width = 90
chain_width = 90
comment_width = 100
enum_discrim_align_threshold = 40
fn_call_width = 90
max_width = 100
single_line_if_else_max_width = 90
single_line_let_else_max_width = 90
struct_field_align_threshold = 40
struct_lit_width = 90
struct_variant_width = 90
