/**
 * API Type Utilities
 *
 * Minimal type helpers for defining plugin API operations.
 * Plugin authors define operations that map friendly names to OpenAPI paths.
 */

import type { HttpMethod, PathsWithMethod } from 'openapi-typescript-helpers';

/** Base type for OpenAPI paths - accepts any object structure. */
export type AnyPaths = object;

/**
 * Structure of an OpenAPI operation (endpoint).
 * Matches the shape generated by openapi-typescript.
 */
export type OperationEntry = {
  parameters?: Record<string, any>;
  requestBody?: Record<string, any>;
  responses: Record<string | number, any>;
};

/**
 * Type constraint for a map of operation names to their definitions.
 * Used internally to validate operation structures.
 */
export type OperationMap<T = any> = T extends Record<string, OperationEntry> ? T : any;

/**
 * Define the operations structure for type-safe API bindings.
 * Transforms an operations interface (from openapi-typescript) into a mapped type
 * with proper index signature for TypeScript compatibility.
 *
 * @typeParam T - The operations interface from openapi-typescript
 */
export type DefineOperations<T extends object = OperationMap> = {
  [K in keyof T]: OperationEntry;
};

/**
 * Maps operation names to their HTTP method and path.
 * Used by plugins to define how friendly operation names map to OpenAPI paths.
 *
 * @typeParam Paths - The paths interface from openapi-typescript
 * @typeParam Operations - The operations interface from openapi-typescript
 *
 * @example
 * ```typescript
 * type MyBindings = OperationBindings<paths, operations>;
 * // { list_users: { method: 'get', path: '/users' }, ... }
 * ```
 */
export type OperationBindings<Paths, Operations extends OperationMap> = Record<
  keyof Operations,
  { method: HttpMethod; path: Extract<keyof Paths, string> }
>;

/**
 * Creates a type-safe factory for defining operation bindings.
 * The factory validates that each operation's method and path are valid for the given OpenAPI spec.
 *
 * @typeParam Paths - The paths interface from openapi-typescript
 * @typeParam Ops - The operations interface from openapi-typescript
 * @returns A factory function that validates and returns the operation bindings
 *
 * @example
 * ```typescript
 * const bindings = createOperationBindingsFactory<paths, operations>()({
 *   list_users: { method: 'get', path: '/users' },
 *   create_user: { method: 'post', path: '/users' },
 * });
 * ```
 */
export const createOperationBindingsFactory =
  <Paths extends object, Ops extends OperationMap>() =>
  <const T extends Record<keyof Ops, { method: HttpMethod; path: any }>>(
    ops: T & {
      [K in keyof T]: T[K] extends { method: infer M; path: infer P }
        ? M extends HttpMethod
          ? P extends PathsWithMethod<Paths, M>
            ? { method: M; path: P }
            : never
          : never
        : never;
    },
  ): T => {
    return ops;
  };
