import type { OpenAPIV3_1 } from 'openapi-types';
import type { StringKeys } from './helpers';
import type {
  AllNodes,
  BaseNode,
  NodeMap,
  NodeNamesUnion,
  NodeTypesUnion,
  NodeUnion,
} from './nodes';

/**
 * Base provided configuration
 *
 * Accepts generated TypeScript types from openapi-typescript (not raw OpenAPI structure).
 * The type system uses clean generated types for type safety, while runtime introspection
 * uses the raw OpenAPI document passed to stately().
 */
export interface StatelyConfig<
  Components = { schemas?: Record<string, any> },
  Paths = {},
  Nodes extends Record<string, BaseNode> = Record<string, BaseNode>,
> {
  components: Components;
  paths: Paths;
  nodes: Nodes;
}

/**
 * Define the Config
 *
 * @example
 * ```typescript
 * type MyStatelyConfig = DefineStatelyConfig<{
 *   components: {},
 *   paths: {},
 *   nodes: {},
 * }>;
 * ```
 */
export type DefineStatelyConfig<
  C extends DefineComponents<{}> = DefineComponents<{}>,
  P extends DefinePaths<{}> = DefinePaths<{}>,
  N extends DefineGeneratedNodes<{}> = DefineGeneratedNodes<{}>,
> = StatelyConfig<C, P, N>;

/**
 * =============================================================================
 * CONFIG DEFINITION HELPERS - "Fill in the form" types for StatelyConfig
 * =============================================================================
 * These helpers guide plugin authors to define the correct types for configs
 * that their plugins expect. Use these when creating custom config types.
 *
 * These accept generated TypeScript types from openapi-typescript, not raw OpenAPI structure.
 */

/**
 * Define the components structure your plugin expects.
 * Typically generated by openapi-typescript with a schemas property.
 *
 * @example
 * ```typescript
 * type MyComponents = DefineComponents<{
 *   schemas: {
 *     MyEntity: { id: string; name: string };
 *     MyOtherType: { value: number };
 *   }
 * }>;
 * ```
 */
export type DefineComponents<
  T extends { schemas?: Record<string, any> } = { schemas?: Record<string, any> }
> = T;

/**
 * Define the component schemas structure your plugin expects.
 * Use this when you only care about schemas, not the full components object.
 *
 * @example
 * ```typescript
 * type MyComponentsSchemas = DefineComponentSchemas<{
 *   MyEntity: { id: string; name: string };
 *   MyOtherType: { value: number };
 * }>;
 * ```
 */
export type DefineComponentSchemas<
  T extends Record<string, any> = Record<string, any>
> = T;

/**
 * Define the paths structure your plugin expects.
 * Typically generated by openapi-typescript as a record of path strings to operations.
 *
 * @example
 * ```typescript
 * type MyPaths = DefinePaths<{
 *   '/api/users': {
 *     get: { responses: { 200: { content: { 'application/json': User[] } } } };
 *   };
 * }>;
 * ```
 */
export type DefinePaths<
  T extends Record<string, any> = Record<string, any>
> = T;

/**
 * Define the generated node structure your plugin expects.
 * All nodes must extend BaseNode.
 *
 * @example
 * ```typescript
 * type MyGeneratedNodes = DefineGeneratedNodes<{
 *   User: ObjectNode;
 *   Post: ObjectNode;
 * }>;
 * ```
 */
export type DefineGeneratedNodes<
  T extends Record<string, any> = Record<string, BaseNode>
> = T extends Record<string, BaseNode> ? T : never;

/**
 * Helper type to ensure OpenAPI spec is typed properly.
 * Accepts JSON imports with readonly modifiers and typed documents.
 *
 * @example
 * ```typescript
 * import openapiDoc from './openapi.json';
 * const doc: DefineOpenApi<typeof openapiDoc> = openapiDoc;
 * ```
 */
export type DefineOpenApi<T> = T extends OpenAPIV3_1.Document<{}>
  ? T
  : T extends Record<string, any>
    ? T & Partial<OpenAPIV3_1.Document<{}>>
    : OpenAPIV3_1.Document<{}>;

export type GeneratedNodeMap<Config extends StatelyConfig> = [StringKeys<Config['nodes']>] extends [
  never,
]
  ? NodeMap
  : {
      [K in StringKeys<Config['nodes']>]: Config['nodes'][K] extends BaseNode
        ? Config['nodes'][K]
        : BaseNode;
    };

export type GeneratedNodes<Config extends StatelyConfig> = AllNodes<GeneratedNodeMap<Config>>;
export type GeneratedNodeUnion<Config extends StatelyConfig> = NodeUnion<GeneratedNodeMap<Config>>;
export type GeneratedNodeNames<Config extends StatelyConfig> = NodeNamesUnion<
  GeneratedNodeMap<Config>
>;
export type GeneratedNodeTypes<Config extends StatelyConfig> = NodeTypesUnion<
  GeneratedNodeMap<Config>
>;
