import type {
  DefineComponentSchemas,
  DefineComponents,
  DefineGeneratedNodes,
  StatelyConfig,
} from '../generated.js';
import type { BaseNode } from '../nodes.js';
import type { DefineTypes, SchemaAugment } from '../plugin.js';
import type { CoreData } from './data.js';
import type { CoreNodeMap, TaggedUnionNode } from './nodes.js';
import type { CorePaths } from './paths.js';
import { CORE_PLUGIN_NAME } from './plugin.js';
import type { CoreUtils } from './utils.js';

export type CoreSchemaTypes<Config extends CoreStatelyConfig> = DefineTypes<{
  // Derived: Extract the actual data payload from Entity union
  EntityData: Extract<Config['components']['schemas']['Entity'], { type: any; data: any }>['data'];
}>;

/**
 * Define the minimum expected schema structure from generated types.
 * Core expects components.schemas to have these types as discriminated unions/primitives
 * (as generated by openapi-typescript), not raw OpenAPI structure.
 */
type CoreComponents = DefineComponents<{
  schemas: DefineComponentSchemas<{
    StateEntry: string;  // Generated as string union type from enum
    Entity: { type: string; data: any };  // Generated as discriminated union
    EntityId: string;
    Summary: { id?: string; name?: string; description?: string };
  }>;
}>;

type CoreComponentInput = StatelyConfig['components'] & CoreComponents;
type CorePathsInput = StatelyConfig['paths'] & CorePaths;

/**
 * Core configuration type that plugin authors can specialize with their own
 * components, paths, and additional nodes. The nodes property automatically
 * includes CoreGenerated nodes merged with any custom nodes passed in.
 */
export interface CoreStatelyConfig<
  C extends CoreComponentInput = CoreComponentInput,
  P extends CorePathsInput = CorePathsInput,
  N extends DefineGeneratedNodes<{}> = Record<never, BaseNode>
> extends StatelyConfig<C, P, DefineGeneratedNodes<{
  Entity: TaggedUnionNode<CoreStatelyConfig>;
}> & N> {}

export type CoreSchemaAugment<Config extends CoreStatelyConfig> = SchemaAugment<
  typeof CORE_PLUGIN_NAME,
  CoreNodeMap<Config>,
  CoreSchemaTypes<Config>,
  CoreData<Config>,
  CoreUtils<Config>
>;
