import type {
  DefineComponentSchemas,
  DefineComponents,
  DefineGeneratedNodes,
  DefinePaths,
  StatelyConfig,
} from '../generated';
import type { NodeMap } from '../nodes';
import type { TaggedUnionNode } from './nodes';
import type { CorePaths } from './paths';

/**
 * Define the minimum expected schema structure from generated types.
 * Core expects components.schemas to have these types as discriminated unions/primitives
 * (as generated by openapi-typescript), not raw OpenAPI structure.
 */
type CoreComponents = DefineComponents<{
  schemas: DefineComponentSchemas<{
    StateEntry: string; // Generated as string union type from enum
    Entity: { type: string; data: { name?: string; [key: string]: any } }; // Generated as discriminated union
    EntityId: string;
    Summary: { id: string; name: string; description?: string | null };
  }>;
}>;

type CoreComponentInput = StatelyConfig['components'] & CoreComponents;
type CorePathsInput = StatelyConfig['paths'] & CorePaths;
type CoreNodesInput<T extends NodeMap = NodeMap> = DefineGeneratedNodes<{
  Entity: TaggedUnionNode<T[keyof T], 'type'>;
}>;

/**
 * Core configuration type that plugin authors can specialize with their own
 * components, paths, and additional nodes. The nodes property automatically
 * includes CoreGenerated nodes merged with any custom nodes passed in.
 *
 * Variance annotations inherited from StatelyConfig ensure Config can only be
 * used covariantly, preventing invariant-causing patterns.
 */
export interface CoreStatelyConfig<
  out C extends CoreComponentInput = CoreComponentInput,
  out P extends CorePathsInput = CorePathsInput,
  out N extends DefineGeneratedNodes = NodeMap,
> extends StatelyConfig<C, P, CoreNodesInput & N> {}

/**
 * Helper to define configuration that builds on Core
 */
export type DefineCoreConfig<
  C extends DefineComponents<object> = CoreStatelyConfig['components'],
  P extends DefinePaths = CoreStatelyConfig['paths'],
  N extends DefineGeneratedNodes = CoreStatelyConfig['nodes'],
> = CoreStatelyConfig<C & CoreComponentInput, P & CorePathsInput, CoreNodesInput & N>;
