import { DefineComponents, DefineComponentSchemas, DefineGeneratedNodes, StatelyConfig } from "../generated";
import { NodeMap } from "../nodes";
import { TaggedUnionNode } from "./nodes";
import { CorePaths } from "./paths";

/**
 * Define the minimum expected schema structure from generated types.
 * Core expects components.schemas to have these types as discriminated unions/primitives
 * (as generated by openapi-typescript), not raw OpenAPI structure.
 */
type CoreComponents = DefineComponents<{
  schemas: DefineComponentSchemas<{
    StateEntry: string;  // Generated as string union type from enum
    Entity: { type: string; data: any };  // Generated as discriminated union
    EntityId: string;
    Summary: { id?: string; name?: string; description?: string | null };
  }>;
}>;

type CoreComponentInput = StatelyConfig['components'] & CoreComponents;
type CorePathsInput = StatelyConfig['paths'] & CorePaths;
type CoreNodesInput = DefineGeneratedNodes<{
  Entity: TaggedUnionNode<CoreStatelyConfig, 'type'>;
}>;

/**
 * Core configuration type that plugin authors can specialize with their own
 * components, paths, and additional nodes. The nodes property automatically
 * includes CoreGenerated nodes merged with any custom nodes passed in.
 */
export interface CoreStatelyConfig<
  C extends CoreComponentInput = CoreComponentInput,
  P extends CorePathsInput = CorePathsInput,
  N extends DefineGeneratedNodes<{}> = NodeMap
> extends StatelyConfig<C, P, CoreNodesInput & N> {}

/**
 * Helper to define configuration that builds on Core
 */
export type DefineCoreConfig<
  C extends DefineComponents<{}> = CoreStatelyConfig['components'],
  P extends CorePathsInput = CoreStatelyConfig['paths'],
  N extends DefineGeneratedNodes<{}> = CoreStatelyConfig['nodes']
> = CoreStatelyConfig<C & CoreComponentInput, P & CorePathsInput, CoreNodesInput & N>;
