import type { DefineOperationMap } from '@stately/ui';

/**
 * Files plugin operation IDs
 *
 * These correspond to the operationIds in the OpenAPI spec generated by the
 * stately-files Rust crate.
 *
 * Backend endpoints:
 * - POST /files/upload - Upload file with multipart form data
 * - POST /files/save   - Save file content directly (compose mode)
 * - GET  /files/list   - List files and directories at path
 */
export const FILES_OPERATION_IDS = {
  listFiles: 'list_files',
  saveFile: 'save_file',
  uploadFile: 'upload_file',
} as const satisfies DefineOperationMap;

export type FilesOperationMap = typeof FILES_OPERATION_IDS;
