import type {
  DefineComponentSchemas,
  DefineComponents,
  DefineGeneratedNodes,
  DefineOperations,
  DefinePaths,
  StatelyConfig,
} from '@stately/schema';
import type { CoreOperations, CorePaths } from './api';
import type { components } from './generated-types';

/**
 * Define the minimum expected schema structure from generated types.
 * Core expects components.schemas to have these types as discriminated unions/primitives
 * (as generated by openapi-typescript), not raw OpenAPI structure.
 */
export type CoreComponents = DefineComponents<{
  schemas: DefineComponentSchemas<
    {
      StateEntry: string; // Generated as string union type from enum
      Entity: { type: string; data: { name?: string; [key: string]: any } }; // Generated as discriminated union
    } & components['schemas']
  >;
}>;

type CoreComponentInput = StatelyConfig['components'] & CoreComponents;
type CoreNodesInput = DefineGeneratedNodes;
type CorePathsInput = StatelyConfig['paths'] & CorePaths;
type CoreOperationsInput = StatelyConfig['operations'] & CoreOperations;

/**
 * Core configuration type that plugin authors can specialize with their own
 * components, paths, and additional nodes. The nodes property automatically
 * includes CoreGenerated nodes merged with any custom nodes passed in.
 *
 * Variance annotations inherited from StatelyConfig ensure Config can only be
 * used covariantly, preventing invariant-causing patterns.
 */
export interface CoreStatelyConfig<
  out C extends CoreComponentInput = CoreComponentInput,
  out P extends CorePathsInput = CorePathsInput,
  out O extends CoreOperationsInput = CoreOperationsInput,
  out N extends DefineGeneratedNodes = DefineGeneratedNodes,
> extends StatelyConfig<C, P, O, CoreNodesInput & N> {}

/**
 * Helper to define configuration that builds on Core
 */
export type DefineCoreConfig<
  C extends DefineComponents<object> = CoreStatelyConfig['components'],
  P extends DefinePaths<any> = CoreStatelyConfig['paths'],
  O extends DefineOperations = CoreStatelyConfig['operations'],
  N extends DefineGeneratedNodes = CoreStatelyConfig['nodes'],
> = CoreStatelyConfig<
  C & CoreComponentInput,
  P & CorePathsInput,
  O & CoreOperationsInput,
  CoreNodesInput & N
>;
